const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('slashIt', {
  loadData: () => ipcRenderer.invoke('load-data'),
  saveData: (data) => ipcRenderer.invoke('save-data', data),
  getDataInfo: () => ipcRenderer.invoke('get-data-info'),
  backupDataNow: () => ipcRenderer.invoke('backup-data-now'),
  openDocumentsDataFolder: () => ipcRenderer.invoke('open-documents-data-folder'),
  restoreDataFromFile: () => ipcRenderer.invoke('restore-data-from-file'),
  exportEarningsReportPdf: (payload) => ipcRenderer.invoke('export-earnings-report-pdf', payload),
  setWindowMode: (mode, options) => ipcRenderer.invoke('set-window-mode', mode, options),
  setFocusWidth: (contentWidth) => ipcRenderer.invoke('set-focus-width', contentWidth),
  setFocusDimensions: (dimensions) => ipcRenderer.invoke('set-focus-dimensions', dimensions),
  hideFocusWindow: () => ipcRenderer.invoke('hide-focus-window'),
  showFocusWindow: () => ipcRenderer.invoke('show-focus-window'),
  onFocusPositionChanged: (callback) => ipcRenderer.on('focus-position-changed', (_event, position) => callback(position)),
  onFocusWindowRestoreRequest: (callback) => ipcRenderer.on('focus-window-restore-request', callback),
  showSessionDrawer: (payload) => ipcRenderer.invoke('show-session-drawer', payload),
  hideSessionDrawer: (immediate = false) => ipcRenderer.invoke('hide-session-drawer', immediate),
  updateSessionDrawer: (payload) => ipcRenderer.invoke('update-session-drawer', payload),
  onDrawerPointerEnter: (callback) => ipcRenderer.on('drawer-pointer-enter', callback),
  onDrawerPointerLeave: (callback) => ipcRenderer.on('drawer-pointer-leave', callback),
  onDrawerSelectTask: (callback) => ipcRenderer.on('drawer-select-task', (_event, index) => callback(index)),
  setScreenOverlay: (visible) => ipcRenderer.invoke('set-screen-overlay', visible),
  triggerCelebration: () => ipcRenderer.invoke('trigger-celebration'),
  stopCelebration: () => ipcRenderer.invoke('stop-celebration'),
  license: {
    getCachedStatus: () => ipcRenderer.invoke('license:get-cached-status'),
    getStatus: () => ipcRenderer.invoke('license:get-status'),
    activate: (payload) => ipcRenderer.invoke('license:activate', payload),
    deactivate: () => ipcRenderer.invoke('license:deactivate'),
    openCheckout: () => ipcRenderer.invoke('license:open-checkout'),
  },
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  isUpdateReadyToInstall: () => ipcRenderer.invoke('is-update-ready-to-install'),
  isUpdateDownloading: () => ipcRenderer.invoke('is-update-downloading'),
  onOpenWhatsNew: (callback) => ipcRenderer.on('open-whats-new', callback),
  pickTaskAttachments: () => ipcRenderer.invoke('pick-task-attachments'),
  openTaskAttachment: (attachment) => ipcRenderer.invoke('open-task-attachment', attachment),
  removeTaskAttachmentFile: (attachment) => ipcRenderer.invoke('remove-task-attachment-file', attachment),
  copyTaskAttachments: (attachments) => ipcRenderer.invoke('copy-task-attachments', attachments),
  copyAttachmentsForTemplate: (attachments) => ipcRenderer.invoke('copy-attachments-for-template', attachments),
  cloneTemplateAttachments: (attachments) => ipcRenderer.invoke('clone-template-attachments', attachments),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  fetchLinkPreview: (url) => ipcRenderer.invoke('fetch-link-preview', url),
});
